# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: push

jobs:
  integration_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install docker
        run: |
          brew install docker docker-machine
          brew install --cask virtualbox
          docker-machine create --driver virtualbox default
          docker-machine env default
          eval "$(docker-machine env default)"
          docker swarm init --advertise-addr 192.168.99.100 --listen-addr 127.0.0.1
          docker stack deploy -c docker/docker-compose.yml app
          docker stack ps app

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          disable-animations: true
          profile: Nexus 5X
          emulator-options: -no-window -no-boot-anim -no-audio
          script: chmod +x gradlew && ./gradlew connectedAndroidCheck
