# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Unit test
      run: ./gradlew testDebug

  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Init swarm"
        run: docker swarm init
      - name: "Build the stack"
        run: docker stack deploy -c docker/docker-compose.yml app
      - name: "Running docker containers"
        run: docker container ls
#      - name: "Run UI Tests"
#        uses: faruktoptas/android-github-actions-emulator@latest


